version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./EntityLite.sln && dotnet publish ./EntityLite.sln -c Release -o ./obj/Docker/publish"
